spring:
  datasource:
    url: jdbc:mysql://39.108.55.93:3306/erp?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    password: 123456
    username: erp
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filter: stat
  jpa:
    show-sql: true
server:
  port: 8095

mybatis:
  type-aliases-package: com.study.entiey
  mapper-locations: classpath:mappers/*.xml

logging:
  level:
    com:
      study:
        model:
          mapper: debug

